name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          apt-fast -y install \
          libdbus-glib-1-dev \
          libdrm-dev \
          libgtk-3-dev \
          libgtk2.0-dev \
          libpango1.0-dev \
          libpulse-dev \
          libx11-xcb-dev \
          nasm
      - name: Run build script
        run: |
          sed -i -e 's/"r21d"/"r21e"/' python/mozboot/mozboot/android.py
          ./mach create-mach-environment
          ./mach build binaries && ./mach gradle geckoview:publishWithGeckoBinariesDebugPublicationToMavenRepository
