name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          apt-fast install libpulse-dev
      - name: Run a multi-line script
        run: |
          ./mach create-mach-environment
          ./mach build
